{
    vol_id: 3,
        surah_data: [
            {
                surah_id: 20,
                surah_name: 'Al-Kahaf',
                live_path: '',
                download_path: null,
                download_flag: null,
                url: [
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(018)alkahaf/al-kahaf(intro).mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(018)alkahaf/rukoo01alkahaf.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(018)alkahaf/rukoo02alkahaf.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(018)alkahaf/rukoo03alkahaf.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(018)alkahaf/rukoo04alkahaf.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(018)alkahaf/rukoo05alkahaf.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(018)alkahaf/rukoo06alkahaf.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(018)alkahaf/rukoo07alkahaf.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(018)alkahaf/rukoo09alkahaf.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(018)alkahaf/rukoo09alkahaf.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(018)alkahaf/rukoo10alkahaf.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(018)alkahaf/rukoo11alkahaf.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(018)alkahaf/rukoo12alkahaf.mp3',
                ]
            },
            {
                surah_id: 21,
                surah_name: 'Maryam',
                live_path: '',
                download_path: null,
                download_flag: null,
                url: [
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(019)ma ryam/maryam(intro).mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(019)maryam/rukoo01maryam.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(019)maryam/rukoo02maryam.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(019)maryam/rukoo03maryam.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(019)maryam/rukoo04maryam.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(019)maryam/rukoo05maryam.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(019)maryam/rukoo06maryam.mp3',
                ]
            },
            {
                surah_id: 22,
                surah_name: 'Taha',
                live_path: '',
                download_path: null,
                download_flag: null,
                url: [
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(020)taha/(intro)taha.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(020)taha/rukoo01taha.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(020)taha/rukoo02taha.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(020)taha/rukoo03taha.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(020)taha/rukoo04taha.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(020)taha/rukoo05taha.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(020)taha/rukoo06taha.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(020)taha/rukoo07taha.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(020)taha/rukoo08taha.mp3',
                ]
            },
            {
                surah_id: 23,
                surah_name: 'Al-Anbiya',
                live_path: '',
                download_path: null,
                download_flag: null,
                url: [
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(021)al-anbia/al-anbia(intro).mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(021)al-anbia/rukoo01alanbia.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(021)al-anbia/rukoo02alanbia.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(021)al-anbia/rukoo03alanbia.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(021)al-anbia/rukoo04alanbia.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(021)al-anbia/rukoo05alanbia.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(021)al-anbia/rukoo06alanbia.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(021)al-anbia/rukoo07alanbia.mp3',
                ]
            },
            {
                surah_id: 24,
                surah_name: 'Al-Hajj',
                live_path: '',
                download_path: null,
                download_flag: null,
                url: [
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(022)al-hajj/al-hajj(intro).mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(022)al-hajj/rukoo01alhajj.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(022)al-hajj/rukoo01alhajj.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(022)al-hajj/rukoo01alhajj.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(022)al-hajj/rukoo01alhajj.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(022)al-hajj/rukoo01alhajj.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(022)al-hajj/rukoo01alhajj.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(022)al-hajj/rukoo01alhajj.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(022)al-hajj/rukoo01alhajj.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(022)al-hajj/rukoo01alhajj.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(022)al-hajj/rukoo01alhajj.mp3',
                ]
            },
            {
                surah_id: 25,
                surah_name: 'Al-Mominoon',
                live_path: '',
                download_path: null,
                download_flag: null,
                url: [
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(023)al-mominoon/al-mominoon(intro).mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(023)al-mominoon/rukoo01mominoon.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(023)al-mominoon/rukoo02mominoon.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(023)al-mominoon/rukoo03mominoon.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(023)al-mominoon/rukoo04mominoon.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(023)al-mominoon/rukoo05mominoon.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(023)al-mominoon/rukoo06mominoon.mp3',
                ],
            },
            {
                surah_id: 26,
                surah_name: 'An-Noor',
                live_path: '',
                download_path: null,
                download_flag: null,
                url: [
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(024)an-noor/an-noor(intro).mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(024)an-noor/rukoo01annoor.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(024)an-noor/rukoo02annoor.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(024)an-noor/rukoo03annoor.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(024)an-noor/rukoo04annoor.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(024)an-noor/rukoo05annoor.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(024)an-noor/rukoo06annoor.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(024)an-noor/rukoo07annoor.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(024)an-noor/rukoo08annoor.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(024)an-noor/rukoo09annoor.mp3',
                ]
            },
            {
                surah_id: 27,
                surah_name: 'Al-Furqan',
                live_path: '',
                download_path: null,
                download_flag: null,
                url: [
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(025)al-furqan/al-furqan(intro).mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(025)al-furqan/rukoo01alfurqan.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(025)al-furqan/rukoo02alfurqan.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(025)al-furqan/rukoo03alfurqan.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(025)al-furqan/rukoo04alfurqan.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(025)al-furqan/rukoo05alfurqan.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(025)al-furqan/rukoo06alfurqan.mp3',
                ]
            },
            {
                surah_id: 28,
                surah_name: 'Ash-Shoara',
                live_path: '',
                download_path: null,
                download_flag: null,
                url: [
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(026)ash-shoara/ash-shoara(intro).mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(026)ash-shoara/rukoo01ashshoara.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(026)ash-shoara/rukoo02ashshoara.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(026)ash-shoara/rukoo03ashshoara.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(026)ash-shoara/rukoo04ashshoara.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(026)ash-shoara/rukoo05ashshoara.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(026)ash-shoara/rukoo06ashshoara.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(026)ash-shoara/rukoo07ashshoara.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(026)ash-shoara/rukoo08ashshoara.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(026)ash-shoara/rukoo09ashshoara.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(026)ash-shoara/rukoo10ashshoara.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(026)ash-shoara/rukoo11ashshoara.mp3',
                ]
            },
            {
                surah_id: 29,
                surah_name: 'An-Namal',
                live_path: '',
                download_path: null,
                download_flag: null,
                url: [
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(027)an-namal/an-namal(intro).mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(027)an-namal/rukoo01annamal.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(027)an-namal/rukoo02annamal.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(027)an-namal/rukoo03annamal.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(027)an-namal/rukoo04annamal.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(027)an-namal/rukoo05annamal.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(027)an-namal/rukoo06annamal.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(027)an-namal/rukoo07annamal.mp3',
                ]
            },
            {
                surah_id: 30,
                surah_name: 'Al-Qasas',
                live_path: '',
                download_path: null,
                download_flag: null,
                url: [
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(028)al-qasas/al-qasas(intro).mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(028)al-qasas/rukoo01alqasas.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(028)al-qasas/rukoo02alqasas.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(028)al-qasas/rukoo03alqasas.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(028)al-qasas/rukoo04alqasas.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(028)al-qasas/rukoo05alqasas.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(028)al-qasas/rukoo06alqasas.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(028)al-qasas/rukoo07alqasas.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(028)al-qasas/rukoo08alqasas.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(028)al-qasas/rukoo09alqasas.mp3',
                ]
            },
            {
                surah_id: 31,
                surah_name: 'Al-Ankaboot',
                live_path: '',
                download_path: null,
                download_flag: null,
                url: [
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(029)al-ankaboot/al-ankaboot(intro).mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(029)al-ankaboot/rukoo01alankaboot.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(029)al-ankaboot/rukoo02alankaboot.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(029)al-ankaboot/rukoo03alankaboot.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(029)al-ankaboot/rukoo04alankaboot.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(029)al-ankaboot/rukoo05alankaboot.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(029)al-ankaboot/rukoo06alankaboot.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(029)al-ankaboot/rukoo07alankaboot.mp3',
                ]
            },
            {
                surah_id: 32,
                surah_name: 'Al-Room',
                live_path: '',
                download_path: null,
                download_flag: null,
                url: [
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(030)ar-room/ar-room(intro).mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(030)ar-room/rukoo01arroom.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(030)ar-room/rukoo02arroom.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(030)ar-room/rukoo03arroom.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(030)ar-room/rukoo04arroom.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(030)ar-room/rukoo05arroom.mp3',
                    'http://download.quranurdu.com/Tafheem-ul-Quran%20by%20Syed%20Moududi/volume03/(030)ar-room/rukoo06arroom.mp3',
                ]
            },
        ],
  },